### PR TITLE
Fix Issue 'Redirecto to wrong URL #187'

### PR DESCRIPTION
**Pull request by MichaelHumplEnBW**
The "Location"-HTTP-Header don't need to be URL-Decoded

### CODE REVIEW

**Comment by MichaelHumplEnBW** [comment]
Im'a very sorry, i work on a solution for the Issue "[Feature Request] Url Resolution Landing Page #189" and do not use a extra branch for this. Now i down know how to sparate the changes.

**Comment by Miboch** [comment]
I'm a little worried about the automatic redirect. While its nice to save a click I can easily imagine edge cases where users get distracted, or minimize the page on their mobile devices, forgetting about it before coming back later.

Personally I would prefer a "Continue" button, but this is so much better than not having the feature at all! 👍

**Comment by MichaelHumplEnBW** [comment]
No Problem, the the newest Version has now auto-redirect.

**Comment by MichaelHumplEnBW** [comment]
Now the html-layout is improved and there is a Submit-Button :-)

**Comment by FBoucher** [comment]
Great Code @MichaelHumplEnBW 
Would you consider updating your code to be more consistent with the other API methods?

The Redirect function is for redirecting a call. It's important that the URLS pass through this one for statistics.

Generating a QRCode could be done in a function named `UrlQRCodeCreate` or something like that.

**Pull request closed without merging**
