### PR TITLE
Added VS solution file

### PR DESCRIPTION
**Pull request by vnbaaij**
For those who like to work with full Visual Studio instead of VS Code.

Also updated NuGet packages and made function project target netcoreapp3.1

### CODE REVIEW

**Comment by FBoucher** [comment]
@vnbaaij thanks for the help.
Let's update the dependency on another issue (#83)

Also, could you keep `appsettings.json` generic no specific URL no ports

**Comment by vnbaaij** [comment]
Reverted the changes in appsettings.json and NuGet updates

**Comment by FBoucher** [comment]
@all-contributors add @vnbaaij for code

**Comment by FBoucher** [comment]
Thanks @vnbaaij

**Pull request merged**
